/**
 * Agent Layer — LLM-driven intent parsing and shot selection
 *
 * Architecture:
 *   - LLMBackend: thin interface for any LLM provider (one method: callLLM)
 *   - BaseAgent: all prompt logic lives here, calls this.backend.callLLM()
 *   - Provider backends: AnthropicBackend, OpenAIBackend, OpenAICompatBackend
 *   - HeuristicAgent: keyword fallback, no API key required
 *
 * Provider selection (set AGENT_PROVIDER in .env):
 *   'claude'           — Anthropic API  (ANTHROPIC_API_KEY)
 *   'openai'           — OpenAI API     (OPENAI_API_KEY)
 *   'openai-compat'    — Any OpenAI-compatible endpoint (OPENAI_COMPAT_BASE_URL + OPENAI_COMPAT_API_KEY)
 *                        Works with: Ollama, vLLM, Together, Groq, DeepSeek, Azure OpenAI, etc.
 *   'none'             — Heuristic fallback (no API key required)
 */
import { REGISTRY, CompositionMeta } from './registry';
import { analyzeKeyframe } from './brightness';

export interface ParsedIntent {
  /** Main theme / title for the video */
  theme: string;
  /** Which composition to use */
  composition: CompositionMeta;
  /** Per-slot search query overrides (optional — falls back to registry defaults) */
  queryOverrides?: string[];
  /** Music style description override (optional) */
  musicStyleOverride?: string;
}

/**
 * Per-clip annotation generated by the LLM based on the actual shot summary.
 * These override or supplement the static `extra` fields from the registry.
 *
 * Fields are composition-aware: only relevant fields are used per composition.
 *   - tone:        'warm' | 'cool'   — color grade direction (SwitzerlandScenic)
 *   - dramatic:    boolean           — slow-motion / emphasis clip (SportsHighlight)
 *   - transition:  'fade' | 'slide'  — per-clip transition override (future use)
 *   - kenBurns:    'zoom-in' | 'zoom-out' | 'pan-left' | 'pan-right'  (NatureWild)
 *   - caption:     string            — override narrative caption if LLM improves it
 *   - textBg:      Record of region→'light'|'dark' — keyframe brightness analysis result.
 *                  Keys match TEXT_REGIONS in brightness.ts (e.g. "NatureWild.caption").
 *                  'light' means the video background is bright → overlay needed.
 *                  Set by HeuristicAgent via keyframe pixel analysis; LLM agents can
 *                  also populate this from vision analysis.
 */
export interface ClipAnnotation {
  tone?:       'warm' | 'cool';
  dramatic?:   boolean;
  transition?: 'fade' | 'slide';
  kenBurns?:   'zoom-in' | 'zoom-out' | 'pan-left' | 'pan-right';
  caption?:    string;
  /** Per-region brightness result from keyframe analysis */
  textBg?:     Record<string, 'light' | 'dark'>;
}

// ─── LLM Backend interface ────────────────────────────────────────────────────

/**
 * Minimal interface any LLM provider must implement.
 * All prompt logic lives in BaseAgent; backends only handle HTTP transport.
 */
export interface LLMBackend {
  callLLM(system: string, user: string): Promise<string>;
}

// ─── Anthropic backend ────────────────────────────────────────────────────────

export class AnthropicBackend implements LLMBackend {
  constructor(
    private apiKey: string,
    private model = 'claude-sonnet-4-6',
  ) {}

  async callLLM(system: string, user: string): Promise<string> {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type':      'application/json',
        'x-api-key':         this.apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model:      this.model,
        max_tokens: 1024,
        system,
        messages: [{ role: 'user', content: user }],
      }),
    });
    if (!res.ok) throw new Error(`Anthropic API error ${res.status}: ${await res.text()}`);
    const data = await res.json() as any;
    return data.content[0].text as string;
  }
}

// ─── OpenAI-compatible backend (OpenAI, Ollama, vLLM, Groq, DeepSeek, …) ─────

export class OpenAICompatBackend implements LLMBackend {
  private baseUrl: string;

  constructor(
    private apiKey: string,
    private model: string,
    /** Base URL — defaults to OpenAI. Override for Ollama/vLLM/etc. */
    baseUrl?: string,
  ) {
    const base = (baseUrl ?? 'https://api.openai.com').replace(/\/$/, '');
    // If caller already includes /v1 (e.g. OpenRouter), don't double-append it
    this.baseUrl = base.endsWith('/v1') ? base : `${base}/v1`;
  }

  async callLLM(system: string, user: string): Promise<string> {
    const res = await fetch(`${this.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type':  'application/json',
        'Authorization': `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model: this.model,
        messages: [
          { role: 'system',  content: system },
          { role: 'user',    content: user   },
        ],
        max_tokens: 1024,
      }),
    });
    if (!res.ok) throw new Error(`LLM API error ${res.status}: ${await res.text()}`);
    const data = await res.json() as any;
    return data.choices[0].message.content as string;
  }
}

// ─── AgentProvider interface ──────────────────────────────────────────────────

/** Compact summary of a user's media library, passed to LLM for dynamic planning. */
export interface LibrarySummary {
  videos: Array<{
    name: string;
    duration: number;
    shotCount: number;
    /** Up to 20 shot summaries sampled from the video */
    sampleSummaries: string[];
    /** Unique mood tags found across sampled shots */
    moods: string[];
    /** Unique scene tags found across sampled shots */
    scenes: string[];
  }>;
}

/** A dynamically generated slot list produced by LLM after seeing the library. */
export interface DynamicPlan {
  /** Theme/title for the video */
  theme: string;
  /** Which registered composition to use as the Remotion template */
  compositionId: string;
  /** Music style description */
  musicStyle: string;
  /** Slot list tailored to what actually exists in the library */
  slots: Array<{
    query: string;
    mood?: string;
    /** Any extra metadata the LLM wants to attach (caption, location, etc.) */
    extra?: Record<string, unknown>;
  }>;
}

export interface AgentProvider {
  parseIntent(userRequest: string): Promise<ParsedIntent>;
  refineQueries(slots: Array<{ defaultQuery: string; mood?: string }>, theme: string): Promise<string[]>;
  /**
   * Given the actual shot summaries returned by ShotAI, produce per-clip
   * visual annotations that drive Remotion special-effects decisions.
   *
   * @param clips  The resolved clip list (summary, optional keyframePath, slot extra)
   * @param compositionId  Which composition is being rendered (determines which fields matter)
   */
  annotateClips(
    clips: Array<{ summary: string; keyframePath?: string; slotExtra?: Record<string, unknown> }>,
    compositionId: string,
  ): Promise<ClipAnnotation[]>;
  /**
   * After seeing what's actually in the user's library, generate a tailored plan:
   * which composition to use and what slots to search for.
   */
  planFromLibrary(userRequest: string, library: LibrarySummary): Promise<DynamicPlan>;
}

// ─── BaseAgent — all prompt logic lives here ──────────────────────────────────

class BaseAgent implements AgentProvider {
  constructor(private backend: LLMBackend) {}

  async parseIntent(userRequest: string): Promise<ParsedIntent> {
    const compositionList = REGISTRY.map(m =>
      `  - ${m.id}: ${m.label} — ${m.description}`
    ).join('\n');

    const system = `你是一个视频混剪规划助手。根据用户的混剪需求，选择最合适的合成风格并提取主题。
只输出 JSON，格式如下：
{
  "theme": "视频主题名称（简短，用做片头片尾标题）",
  "compositionId": "CyberpunkCity | TravelVlog | MoodDriven",
  "musicStyleOverride": "（可选）英文音乐风格描述，留空则用默认"
}`;

    const user = `可选合成风格：
${compositionList}

用户需求：${userRequest}`;

    const raw = await this.backend.callLLM(system, user);
    let parsed: any;
    try {
      parsed = JSON.parse(raw.replace(/```json\n?|\n?```/g, '').trim());
    } catch {
      throw new Error(`Agent parseIntent: invalid JSON response: ${raw}`);
    }

    const meta = REGISTRY.find(m => m.id === parsed.compositionId) ?? REGISTRY[0];
    return {
      theme:              parsed.theme ?? userRequest.slice(0, 30),
      composition:        meta,
      musicStyleOverride: parsed.musicStyleOverride || undefined,
    };
  }

  async refineQueries(
    slots: Array<{ defaultQuery: string; mood?: string }>,
    theme: string,
  ): Promise<string[]> {
    const slotList = slots.map((s, i) =>
      `  ${i + 1}. default: "${s.defaultQuery}"  mood: ${s.mood ?? 'any'}`
    ).join('\n');

    const system = `Shot search query optimizer. For each slot, write a short English phrase (5–8 words) describing what the camera sees. Used for semantic vector search — concise beats verbose.
Output ONLY a JSON array of the same length. English only.`;

    const user = `Theme: ${theme}
Slots:
${slotList}

Output JSON array:`;

    const raw = await this.backend.callLLM(system, user);
    try {
      const arr = JSON.parse(raw.replace(/```json\n?|\n?```/g, '').trim());
      if (!Array.isArray(arr) || arr.length !== slots.length) {
        throw new Error(`Expected array of length ${slots.length}`);
      }
      return arr as string[];
    } catch (e) {
      console.warn(`   ⚠  Agent refineQueries failed (${(e as Error).message}), using defaults`);
      return slots.map(s => s.defaultQuery);
    }
  }

  async annotateClips(
    clips: Array<{ summary: string; keyframePath?: string; slotExtra?: Record<string, unknown> }>,
    compositionId: string,
  ): Promise<ClipAnnotation[]> {
    const fieldHints: Record<string, string> = {
      SwitzerlandScenic: '"tone": "warm"|"cool" — warm for sunshine/meadow/sunset, cool for snow/glacier/water',
      SportsHighlight:   '"dramatic": true|false — true for goals/key moments/emotional close-ups, false for regular play',
      NatureWild:        '"kenBurns": "zoom-in"|"zoom-out"|"pan-left"|"pan-right" — choose based on subject (animal approaching=zoom-in, wide landscape=zoom-out, moving subject=pan)',
    };
    const relevantFields = fieldHints[compositionId] ?? '"tone": "warm"|"cool"';

    const clipList = clips.map((c, i) =>
      `  ${i + 1}. summary: "${c.summary}"${c.slotExtra?.caption ? `  caption_hint: "${c.slotExtra.caption}"` : ''}`
    ).join('\n');

    const system = `你是一个视频剪辑视效助手。根据每个镜头的语义描述，为每个镜头生成精准的视觉特效注解。
只输出 JSON 数组，每个元素只包含相关字段（不相关字段省略）。
当前合成需要的字段：${relevantFields}
输出格式示例：[{"tone":"cool"},{"tone":"warm","dramatic":true},...]
元素数量必须与输入完全相同。`;

    const user = `合成ID：${compositionId}
镜头列表（共 ${clips.length} 个）：
${clipList}

请为每个镜头生成视效注解，输出 JSON 数组。`;

    const raw = await this.backend.callLLM(system, user);
    let annotations: ClipAnnotation[];
    try {
      const arr = JSON.parse(raw.replace(/```json\n?|\n?```/g, '').trim());
      if (!Array.isArray(arr) || arr.length !== clips.length) {
        throw new Error(`Expected array of length ${clips.length}`);
      }
      annotations = arr as ClipAnnotation[];
    } catch (e) {
      console.warn(`   ⚠  annotateClips failed (${(e as Error).message}), skipping annotations`);
      annotations = clips.map(() => ({}));
    }

    // Augment with keyframe brightness analysis (fixed algorithm, no LLM)
    for (let i = 0; i < clips.length; i++) {
      const kf = clips[i].keyframePath;
      if (kf) annotations[i].textBg = analyzeKeyframe(kf, compositionId);
    }
    return annotations;
  }

  async planFromLibrary(userRequest: string, library: LibrarySummary): Promise<DynamicPlan> {
    const compositionList = REGISTRY.map(m =>
      `  - ${m.id}: ${m.label} — ${m.description}`
    ).join('\n');

    const libraryDesc = library.videos.map(v =>
      `  【${v.name}】时长${Math.round(v.duration / 60)}分钟，${v.shotCount}个镜头\n` +
      `    情绪: ${v.moods.slice(0, 6).join(', ') || '未知'}\n` +
      `    场景: ${v.scenes.slice(0, 6).join(', ') || '未知'}\n` +
      `    镜头样本: ${v.sampleSummaries.slice(0, 8).map(s => `"${s.slice(0, 60)}"`).join(' / ')}`
    ).join('\n\n');

    const system = `你是一个视频混剪规划师。用户有一个视频素材库，你需要：
1. 分析库里实际存在的素材内容
2. 根据用户需求和库里有的内容，选择最合适的合成模板
3. 生成专门针对这个库的镜头搜索槽位列表（不要用通用词，要用能在这个库里搜到东西的词）

只输出 JSON，格式如下：
{
  "theme": "视频主题（简短标题）",
  "compositionId": "选择的合成ID",
  "musicStyle": "英文音乐风格描述",
  "slots": [
    { "query": "搜索词（针对这个库定制）", "mood": "calm|fast|slow|urban", "extra": {} },
    ...
  ]
}
slots数量建议6-10个，与选择的合成模板匹配。`;

    const user = `可用合成模板：
${compositionList}

用户素材库内容：
${libraryDesc}

用户需求：${userRequest}`;

    const raw = await this.backend.callLLM(system, user);
    let parsed: any;
    try {
      parsed = JSON.parse(raw.replace(/```json\n?|\n?```/g, '').trim());
    } catch {
      throw new Error(`planFromLibrary: invalid JSON response: ${raw}`);
    }

    return {
      theme:         parsed.theme ?? userRequest.slice(0, 30),
      compositionId: parsed.compositionId ?? REGISTRY[0].id,
      musicStyle:    parsed.musicStyle ?? 'cinematic ambient',
      slots:         Array.isArray(parsed.slots) ? parsed.slots : [],
    };
  }
}

// ─── Heuristic fallback (no API key) ──────────────────────────────────────────

class HeuristicAgent implements AgentProvider {
  async parseIntent(userRequest: string): Promise<ParsedIntent> {
    const req = userRequest.toLowerCase();
    let meta: CompositionMeta;
    if (req.includes('赛博') || req.includes('cyberpunk') || req.includes('霓虹') || req.includes('夜景')) {
      meta = REGISTRY.find(m => m.id === 'CyberpunkCity')!;
    } else if (req.includes('旅行') || req.includes('vlog') || req.includes('城市名') || req.includes('地标')) {
      meta = REGISTRY.find(m => m.id === 'TravelVlog')!;
    } else {
      meta = REGISTRY.find(m => m.id === 'TravelVlog')!;
    }
    const theme = userRequest.split(/[,，。\n]/)[0].slice(0, 20).trim();
    console.log(`   ℹ  HeuristicAgent: no API key — selected "${meta.label}" for "${theme}"`);
    return { theme, composition: meta };
  }

  async refineQueries(slots: Array<{ defaultQuery: string }>, _theme: string): Promise<string[]> {
    return slots.map(s => s.defaultQuery);
  }

  async annotateClips(
    clips: Array<{ summary: string; keyframePath?: string }>,
    compositionId: string,
  ): Promise<ClipAnnotation[]> {
    return clips.map(c => {
      const ann: ClipAnnotation = {};
      if (c.keyframePath) ann.textBg = analyzeKeyframe(c.keyframePath, compositionId);
      return ann;
    });
  }

  async planFromLibrary(userRequest: string, library: LibrarySummary): Promise<DynamicPlan> {
    // Heuristic: reuse parseIntent to pick a composition, then use registry defaults as slots
    const intent = await this.parseIntent(userRequest);
    return {
      theme:         intent.theme,
      compositionId: intent.composition.id,
      musicStyle:    intent.musicStyleOverride ?? intent.composition.musicStyle,
      slots:         intent.composition.shotSlots.map(s => ({
        query: s.query,
        mood:  s.mood,
        extra: s.extra,
      })),
    };
  }
}

// ─── Factory ──────────────────────────────────────────────────────────────────

export type AgentProviderName = 'claude' | 'openai' | 'openai-compat' | 'none';

export interface CreateAgentOptions {
  provider: AgentProviderName;
  apiKey?: string;
  model?: string;
  /** Only for 'openai-compat': base URL of the compatible endpoint */
  baseUrl?: string;
}

/**
 * createAgent — instantiate the right backend and wrap it in BaseAgent.
 *
 * Examples:
 *   createAgent({ provider: 'claude', apiKey: '...' })
 *   createAgent({ provider: 'openai', apiKey: '...', model: 'gpt-4o' })
 *   createAgent({ provider: 'openai-compat', apiKey: '...', model: 'deepseek-chat', baseUrl: 'https://api.deepseek.com' })
 *   createAgent({ provider: 'openai-compat', apiKey: 'ollama', model: 'llama3', baseUrl: 'http://localhost:11434' })
 *   createAgent({ provider: 'none' })  // keyword heuristics only
 */
export function createAgent(opts: CreateAgentOptions): AgentProvider;
/** @deprecated Pass an options object instead */
export function createAgent(provider: AgentProviderName, apiKey?: string, model?: string): AgentProvider;
export function createAgent(
  optsOrProvider: CreateAgentOptions | AgentProviderName,
  apiKey?: string,
  model?: string,
): AgentProvider {
  const opts: CreateAgentOptions =
    typeof optsOrProvider === 'string'
      ? { provider: optsOrProvider as AgentProviderName, apiKey, model }
      : optsOrProvider;

  if (opts.provider === 'claude') {
    if (!opts.apiKey) {
      console.warn('   ⚠  AGENT_PROVIDER=claude but ANTHROPIC_API_KEY is not set — falling back to heuristic');
      return new HeuristicAgent();
    }
    return new BaseAgent(new AnthropicBackend(opts.apiKey, opts.model ?? 'claude-sonnet-4-6'));
  }

  if (opts.provider === 'openai') {
    if (!opts.apiKey) {
      console.warn('   ⚠  AGENT_PROVIDER=openai but OPENAI_API_KEY is not set — falling back to heuristic');
      return new HeuristicAgent();
    }
    return new BaseAgent(new OpenAICompatBackend(opts.apiKey, opts.model ?? 'gpt-4o'));
  }

  if (opts.provider === 'openai-compat') {
    if (!opts.apiKey || !opts.baseUrl) {
      console.warn('   ⚠  openai-compat requires apiKey + baseUrl — falling back to heuristic');
      return new HeuristicAgent();
    }
    return new BaseAgent(new OpenAICompatBackend(opts.apiKey, opts.model ?? 'default', opts.baseUrl));
  }

  return new HeuristicAgent();
}
